### PR TITLE
security-package/issues/171: Default(pre-filled) value should be added to the "Policy" in Admin Panel for Security.txt settings

### LINKED ISSUE #171: Default(pre-filled) value should be added to the "Policy" in Admin Panel for Security.txt settings
Based on DEMO meeting and discussion next changes should be implemented 

1. The default value should be added to the "Policy" field.
**Value to add:** _https://magento.com/security_

2. Hint message under the "Policy" field should be removed 
**Value to remove:** _Example: https://example.com/security-policy.html_

demo_security_txt

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Description (*)

- Updated system.xml

- Added default values, created config.xml

- Updated translate file (i18n), was removed unused value

### Fixed Issues (if relevant)

1. magento/security-package#171: Default(pre-filled) value should be added to the "Policy" in Admin Panel for Security.txt settings

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by lenaorobei — DISMISSED** [review]

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
image

**Comment by lenaorobei** [comment]
@magento run Unit Tests, Functional Tests B2B

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run Database Compare

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run Static Tests

**Comment by lenaorobei** [comment]
Static failures related to 2FA module http://10.234.216.88:8080/job/Static-Tests/7145/

**Comment by lenaorobei** [comment]
@magento run Static Tests, Functional Tests EE, Functional Tests B2B

**Pull request merged**
