### PR TITLE
[Arrows] MC-34344: AdminLoginAfterJSMinificationTest does not properly enable minification

### PR DESCRIPTION
**Pull request by namlier**
### Bug - P1
* [MC-34344](https://jira.corp.magento.com/browse/MC-34344) AdminLoginAfterJSMinificationTest does not properly enable minification

### Related Pull Requests

- CE https://github.com/magento-commerce/magento2ce/pull/6147

### CE Checklist

- [ ] PR is green on M2 Quality Portal
- [ ] Jira issues have accurate summary, meaningful description and have links to relevant documentation at the story/task level
- [ ] Semantic Version build failure is approved by architect (if build is red) <Architect Name>
- [ ] Pull Request approved by architect <Architect Name>
- [ ] Pull Request quality review performed by <name>
- [ ] All unstable functional acceptance tests are isolated (if any)
- [ ] All linked Zephyr tests are approved by PO and have Ready to Use status
- [ ] Travis CI build is green (for mainline CE only)
- [ ] Jenkins Unit, Extended FAT CE, Extended FAT EE and Extended FAT B2B builds are green

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run Functional Tests EE

**Comment by zakdma** [comment]
@magento run Functional Tests EE

**Comment by zakdma** [comment]
@magento run Functional Tests EE

**Comment by zakdma** [comment]
@magento run Functional Tests EE

**Review by dvoskoboinikov — APPROVED** [review]

**Pull request merged**
