### PR TITLE
security-package: Added try/catch to Magento\ReCaptchaUi\Model\RequesttHandler

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Description (*)
Added try/catch construction to RequesttHandler class for to capture exceptions.

### Fixed Issues (if relevant)
#197 

### Manual testing scenarios (*)

1. Enable reCaptcha v2 (I an not Robot) for Admin Forgot Password
2. Add to reCaptcha v2 (I an not Robot) settings API keys test/test
3. Enable reCaptcha v2 (I an not Robot) for Admin Forgot Password
4. Open the page Admin Forgot Password (host/admin/admin/auth/forgotpassword/)
5. Fill form and try to send
6. Will returned fatal error, with error message report

There_has_been_an_error_processing_your_request

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Delta** [comment]
@engcom-Kilo issue with exception is fixed, but seems like we have redurant error message `Please enter an email address.` if email and magento CAPTCHA were entered correctly:
 
image

**Comment by engcom-Delta** [comment]
@engcom-Kilo @engcom-Foxtrot @naydav 
Generally, PR fix initial issue with exception error.
There is some cases that need to be approved as expected behavior or need to be fixed
**Case 1:** Wrong API keys for reCAPTCHA v2 ("I am not a robot")
**Result when try submit form:** Additional error message "Please enter an email address"
image

image

image

**Case 2:** Wrong API keys for reCAPTCHA v2-v3 Invisible
**Result when try submit form:** Error in console, form is not submitting
image

image

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Initial issue is fixed
Testing results:
**Case 1:** Wrong API keys for reCAPTCHA v2 ("I am not a robot")
**Result when try submit form:** Additional error message "Please enter an email address"
image

image

image

**Case 2:** Wrong API keys for reCAPTCHA v2-v3 Invisible
**Result when try submit form:** Error in console, form is not submitting
image

image


**Case 3** [:heavy_check_mark: issue #197 is fixed]:  reCAPTCHA v2 ("I am not a robot") is unchecked or  reCAPTCHA v2 ("I am not a robot") API Secret Key is incorrect
**Result**:
#175PrPayPal

**Case 4**:  reCAPTCHA v2-v3 Invisible API Secret Key is incorrect
**Result**:
#175Paypalv2v3

**Comment by naydav** [comment]
Case 2: Wrong API keys for reCAPTCHA v2-v3 Invisible
It's should be investigated and fixed in https://github.com/magento/security-package/pull/191
The PR contains JS refactoring.

Case 4: reCAPTCHA v2-v3 Invisible API Secret Key is incorrect
Should be extracted in a separate ticket. The problem is related to incorrect validation message.

@engcom-Delta thank you for QA

**Pull request merged**
