### PR TITLE
Fix check if place-order-recaptcha component is set

### PR DESCRIPTION
**Pull request by basvanpoppel**
…ptcha-container

### Description (*)

The place-order-recaptcha component is set within the place-order-recaptcha-container. The check was looking for the component on the wrong place - therefor the component was loaded while recaptcha was disabled.

### Fixed Issues (if relevant)

1. magento/magento2#33741: JS error in console on checkout when if recaptcha for checkout/placing order is not enabled

### Manual testing scenarios (*)

1. Make sure 'Stores > Configuration > Security > Google reCAPTCHA Storefront > Storefront > Enable for Checkout/Placing Order' is set to 'No'
2. Add a product to cart
2. Go to checkout
3. Open element inspector, no JS error. (or check source: no place-order-recaptcha component in js layout)

### Questions or comments

Do I need to add a unit test here? The fix is simple. Please let me know if anything else is needed.

### Contribution checklist (*)
 - [x] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by tuna2smc** [comment]
@magento run all tests

**Comment by nathanjosiah** [comment]
@tuna2smc @basvanpoppel  Are you still working on this PR?

**Comment by basvanpoppel** [comment]
@nathanjosiah the PR is ready for review. Is there anything I can do?

**Review by nathanjosiah — APPROVED** [review]

**Comment by nathanjosiah** [comment]
Approved from my end, before I can process this PR please pull latest `develop` and stabilize your builds.

**Comment by nathanjosiah** [comment]
@basvanpoppel Are you able to stabilize your PR?

**Comment by basvanpoppel** [comment]
Hi @nathanjosiah 

Sorry for the late reply, i was away for a few weeks and forgot to reply. I've updated my branch, all looks fine now.

**Comment by nathanjosiah** [comment]
@magento run all tests

**Comment by nathanjosiah** [comment]
@magento import pr to https://github.com/magento-commerce/security-package

**Comment by nathanjosiah** [comment]
@magento import pr to https://github.com/magento-commerce/security-package

**Comment by m2-github-services** [comment]
@nathanjosiah the Pull Request is successfully imported.

**Comment by nathanjosiah** [comment]
Merged via https://github.com/magento-commerce/security-package/pull/54

**Comment by Aquive** [comment]
In which version of Magento is or will this be fixed?

**Comment by nathanjosiah** [comment]
@Aquive the fix is merged and will be part of 2.4.4 which is [scheduled to GA March 8 2022](https://devdocs.magento.com/release/)

**Pull request closed without merging**
