### PR TITLE
security-package/issues/154: Add reCAPTCHA support for customer account edit.

### LINKED ISSUE #154: Add reCAPTCHA support for customer account edit.
customer/account/edit/ page should contain reCAPTCHA.

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
…

### Fixed Issues (if relevant)

1. https://github.com/magento/security-package/issues/154: Add reCAPTCHA support for customer account edit.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by naydav** [comment]
@magento run all tests

**Comment by naydav** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**

- reCAPTCHA v2 ("I am not a robot")
#155PRV2NotRobot

- reCAPTCHA v2 Invisible
#155PrV2Inv

- reCAPTCHA v3 Invisible
#155PrV3

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
