### PR TITLE
security-package/issues/204: Fix for few reCAPTCHA Invisible type on page.

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. magento/security-package#204: Recaptch badge is not shown on PayPal PayflowPro payment form if 'Invisible Badge Position' is 'Bottom Left/Right'

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Delta** [comment]
@engcom-Kilo I checked PR with latest commit [1218937](https://github.com/magento/security-package/commit/12189370eac7098a1912d19ec411ee985484cf0b) and found issue: recapthca badge is shown on every page when it is enabled only for Customer Login

**Manual testing scenario:**

- Configure reCAPTCHA v2 Invisible:
- - Invisible Badge Position = Bottom Right
- Set Enable for Customer Login=reCAPTCHA v2 Invisible
- Save config and flush cache
- Go to home page, contact us page, create new account page

**Result:**
:x: Recaptcha badge is shown on every page 
image

image

image

**Comment by engcom-Kilo** [comment]
> @engcom-Kilo I checked PR with latest commit [1218937](https://github.com/magento/security-package/commit/12189370eac7098a1912d19ec411ee985484cf0b) and found issue: recapthca badge is shown on every page when it is enabled only for Customer Login

Yes,
this issue by Google reCAPTCHA

If hidden block (login pop-up block present on each page),
will incorrect rendering reCAPTCHA block, and need show reCAPTCHA block in not hidden block. 
So, if on page exist reCAPTCHA & type is Invisible with non inline size, will show reCAPTCHA block at the bottom.

**Comment by engcom-Kilo** [comment]
@engcom-Delta 
Added pull request https://github.com/magento/security-package/pull/219 , with additional settings for Customer Login Popup.

**Comment by naydav** [comment]
Closed due to https://github.com/magento/security-package/pull/237

**Pull request closed without merging**
