### PR TITLE
magento/security-package#224: Recaptcha badge is not shown on checkout login form if 'Invisible Badge Position' is 'Bottom Left/Right' V1

### LINKED ISSUE #224: Recaptcha badge is not shown on checkout login form if 'Invisible Badge Position' is 'Bottom Left/Right'
### Preconditions (*)

1. Magento with security-package 1.0-develop
2. Simple product is created
3. Customer is created

### Steps to reproduce (*)

1. Configure reCAPTCHA Invisible:
- Enable for Customer Login=reCAPTCHA v2/v3 Invisible
2. Invisible Badge Position=Bottom Left or Right
3. Add product to cart
4. Go to checkout page

### Expected result (*)

1. Recaptcha badge is shown on checkout login form

### Actual result (*)

1. Recaptcha badge is **not** shown on checkout login form
Peek 2020-05-19 16-51

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Fixed Issues (if relevant)

1. Fixes magento/security-package#224: Recaptcha badge is not shown on checkout login form if 'Invisible Badge Position' is 'Bottom Left/Right'

### Manual testing scenarios (*)

1. See magento/security-package#224

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
Closed in favour of https://github.com/magento/security-package/pull/237.

**Comment by naydav** [comment]
Closed in favor of https://github.com/magento/security-package/pull/237

**Pull request closed without merging**
