### PR TITLE
magento/security-package#242: ReCAPTCHA v2 ("I am not a robot") for Newsletter Subscription displays with error.

### LINKED ISSUE #242: ReCAPTCHA v2 ("I am not a robot") for Newsletter Subscription displays with error
### Preconditions (*)

1. Magento 2.4-develop
2. Keys for all reCAPTCHA added and saved in Admin
3. Enable Invisible reCAPTCHA in Newsletter Subscription = reCAPTCHA v2 ("I am not a robot")
and for example - Enable for Contact Us = reCAPTCHA v2 ("I am not a robot")

### Steps to reproduce (*)

1. Open Contact Us page
2. Open any page that contains "Newsletter Subscription" field 

### Expected result (*)

1. The title in the admin panel should be without the word "Invisible" - "Enable reCAPTCHA in Newsletter Subscription"
2. Both reCAPTCHAs are shown correctly. No error
3. ReCAPTCHA v2 (“I'm not a robot”) should be displayed below the “Subscribe to Newsletter” field

### Actual result (*)

ReCAPTCHA v2 ("I am not a robot") for Newsletter Subscription displays with error "This site key is not enabled for the invisible captcha."
Screenshot_49

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Fixed Issues (if relevant)

1. Fixes magento/security-package#242: ReCAPTCHA v2 ("I am not a robot") for Newsletter Subscription displays with error.

### Manual testing scenarios (*)

1. See magento/security-package#242: ReCAPTCHA v2 ("I am not a robot") for Newsletter Subscription displays with error.

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed
Result

Screenshot_69

Screenshot_70

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by naydav** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
All recaptcha badges for newsletter are shown properly
- reCAPTCHA v2 ("I am not a robot")
#244PRV2NotRobot


- reCAPTCHA v2/V3 Invisible
#244PRV2_V3inv

**Comment by naydav** [comment]
`1.0-develop` contains these changes.

**Pull request closed without merging**
