### PR TITLE
[MFTF] [1.0.0-develop] MQE-2194: fix mftf tests static check failures

### PR DESCRIPTION
**Pull request by jilu1**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by jilu1** [comment]
This PR is critical for MFTF team to enable static checks on builds. Can someone please review and process it as a priority?

**Comment by jilu1** [comment]
This PR is critical for MFTF team to enable static checks on builds. @ishakhsuvarov Can you please review and process it as a priority?

**Review by nathanjosiah — APPROVED** [review]

**Comment by nathanjosiah** [comment]
@magento run help

**Comment by nathanjosiah** [comment]
@magento run all tests

**Comment by jilu1** [comment]
@magento run all tests

**Comment by jilu1** [comment]
@magento run ee tests

**Comment by jilu1** [comment]
@nathanjosiah Tests are green and pr ready to merge

**Pull request merged**
