### PR TITLE
Update donatj/phpuseragentparser in TwoFactorAuth

### PR DESCRIPTION
**Pull request by donatj**
### Description (*)

Upgrades `donatj/phpuseragentparser` major version. The 0.x branch will soon be unmaintained.

I maintain `donatj/phpuseragentparser` and can state that no changes are necessary as there is a backwards compatibility layer.

### Contribution checklist (*)
 - [x] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by donatj** [comment]
I signed the CLA despite it saying I have not.

**Comment by nathanjosiah** [comment]
Opened internal ticket https://jira.corp.magento.com/browse/AC-1201

**Comment by nathanjosiah** [comment]
`donatj/phpuseragentparser` is no longer used by security-package and will be removed in scope of internal ticket https://jira.corp.magento.com/browse/AC-7 and PR https://github.com/magento/security-package/pull/315

**Comment by donatj** [comment]
Sad day

**Pull request closed without merging**
