### PR TITLE
magento/security-package#127: Configuration cannot be saved in scope that is different from Default Config

### LINKED ISSUE #127: Configuration cannot be saved in scope that is different from Default Config
For now configuration scope for Security.txt is defined as by `store view`
image
That leads to following issue: configuration cannot be saved in scope that is different from `Default Config`

**Steps to reproduce:**
1. Create Website:
a. Name = United Kingdom 
b. Code = uk_website 
c. Sort Order = 1

2. Create Store :
a.	Web Site = United Kingdom
b.	Name = UK
c.	Code = uk_store
d.	Root Category = Default Category

3. Create Store View:
a.	Store = UK
b.	Name =  UNITED KINGDOM - ENGLISH
c.	Code = uk_en
d.	Status = Enabled
e.	Sort Order = 1

4. Enable Security.txt and fill all fileds
5. Go to Stores->Configuration
6. Change `Scope:` to `United Kingdom`
7. Edit some fields and click `Save Config`
**Result:**
:x: Configuration is not saved for current website scope
image

8. Change `Scope:` to `UNITED KINGDOM - ENGLISH`
9. Edit some fields and click `Save Config`
**Result:**
:x: Configuration is not saved for current store view scope
image

### PR DESCRIPTION
**Pull request by lenaorobei**
### Fixed Issues (if relevant)

1. magento/security-package#127: Configuration cannot be saved in scope that is different from Default Config

### Manual testing scenarios (*)

See issue

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**

- Saved config for second website

image

- Security.txt data for second website

image

image

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
AUR Functional https://m2build-ur.devops.magento.com/view/all/job/All-User-Requested-Tests/33073/

**Pull request merged**
