### PR TITLE
Removing the unused `phpseclib/phpseclib` composer package in TwoFactorAuth

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR aims to remove the unused `phpseclib/phpseclib` composer package.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [x] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
Hi @nathanjosiah, could you confirm that this package is still used within TwoFactorAuth? Unfortunately, I couldn't find any usages so far. Please let me know if we're safe to get rid of this dependency.

Thank you.

**Comment by eduard13** [comment]
@magento run WebAPI Tests, Functional Tests CE

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by andrewbess — APPROVED** [review]

**Comment by nathanjosiah** [comment]
@magento import code to https://github.com/magento-commerce/security-package

**Comment by nathanjosiah** [comment]
@magento import code to https://github.com/magento-commerce/security-package

**Comment by nathanjosiah** [comment]
@magento import code to magento-commerce/security-package

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-commerce/security-package

**Pull request merged**
