### PR TITLE
magento/security-package#203: Recaptch badge with German language is not shown fully on Product Review tab

### LINKED ISSUE #203: reCAPTCHA badge with several language is not shown fully
### Preconditions (*)

1. Magento with security-package 1.0-develop
2. Simple product is created

### Steps to reproduce (*)

1. Configure reCAPTCHA v2 Invisible with Language Code=de
2. Set Enable for Product Review=reCAPTCHA v2 Invisible
3. Go to product detail page
4. Open Review tab

### Expected result (*)

1. Recaptcha badge is shown fully without any cuts

### Actual result (*)

1. 
RegressionDeLanguage

Should be fixed and tested for all places where reCAPCHA is shown.

**UPD. Examples** 
## Also affected PayPal PayflowPro payment form
image

##  login during Checkout
recapha3_241-alpha2

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Fixed Issues (if relevant)

1. Fixes magento/security-package#203: Recaptch badge with German language is not shown fully on Product Review tab

### Manual testing scenarios (*)

1. See magento/security-package#203: Recaptch badge with German language is not shown fully on Product Review tab

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Recaptcha badges are shown propely
- reCAPTCHA v2 ("I am not a robot")
#254PRV2NotRobot

- reCAPTCHA v2/V3 Invisible
#254PRV2_V3inv

**Comment by engcom-Foxtrot** [comment]
@magento run all tests Functional Tests EE

**Review by nathanjosiah — APPROVED** [review]

**Pull request merged**
