### PR TITLE
Fixed invalid html link logout in 2fa screen auth

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Previous html render li without ul wrapper outside
=> Not valid html standards

Before this patch markup

div > li (Miss ul)

After this patch markup

div > ul > li

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by nathanjosiah** [comment]
Closing old issues. If you would like to work on this please let me know and we will reopen so you can stabilize your builds.

**Comment by mrtuvn** [comment]
no after 8months no response from internal i don't want to work with

**Pull request closed without merging**
