### PR TITLE
290 - Mark interfaces as api, refactoring interfaces

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)
This PR created to mark interfaces as api, also added small code refactoring changes

### Fixed Issues (if relevant)

1. magento/security-package#290 Mark interfaces and blocks as API

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by AndreyChorniy** [comment]
@magento run all tests

**Comment by nathanjosiah** [comment]
@magento run all tests against 2.4.3-develop

**Comment by nathanjosiah** [comment]
@AndreyChorniy Can you pull the latest code into your branch. I think that's the bulk of the failures in the builds.

**Comment by nathanjosiah** [comment]
@magento import code to https://github.com/magento-cia/security-package

**Comment by nathanjosiah** [comment]
@magento import code to https://github.com/magento-commerce/security-package

**Comment by nathanjosiah** [comment]
@magento import code to https://github.com/magento-commerce/security-package

**Comment by magento-engcom-team** [comment]
@nathanjosiah the branch with code successfully imported into`magento-commerce/security-package` repository. Branch name: `imported-magento-security-package-294`.

**Comment by fredden** [comment]
https://github.com/magento/security-package/commit/8d5c176194b535f379d985d130d6999edb08e00d

**Pull request closed without merging**
