### PR TITLE
security-package/issues/156: Added ReCaptcha for Share Wishlist

### LINKED ISSUE #156: Add reCAPTCHA support for share wishlist form.
Form on wishlist/index/share/wishlist_id/:id/ page should contain reCAPTCHA.

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. magento/security-package#156: Add reCAPTCHA support for share wishlist form.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Delta** [comment]
@engcom-Kilo Could you add space between recaptcha badge and "Share Wish List" button?
image

**Comment by engcom-Kilo** [comment]
@engcom-Delta 
Updated,
added CSS

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Kilo** [comment]
@magento Please run all test

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by naydav** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Story

**Comment by nathanjosiah** [comment]
@magento import code to https://github.com/magento-commerce/security-package

**Comment by nathanjosiah** [comment]
@magento import code to https://github.com/magento-commerce/security-package

**Comment by magento-engcom-team** [comment]
@nathanjosiah the branch with code successfully imported into`magento-commerce/security-package` repository. Branch name: `imported-magento-security-package-158`.

**Comment by nathanjosiah** [comment]
This is being handled internally in scope of AC-463

**Pull request closed without merging**
