### PR TITLE
Updated endroid/qr-code to 4.3.5

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

Updated endroid/qr-code dependency to the latest version (4.3.5).

### Fixed Issues (if relevant)

1. magento/magento2#34101

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]

**Comment by xmav** [comment]
@anzin Could you please do smoke manual test to verify changed code ?

**Comment by anzin** [comment]
@magento run all tests with env PHP 8.0

**Comment by anzin** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run Functional Tests EE

**Comment by xmav** [comment]
test build with new library dependency is in progress

**Comment by xmav** [comment]
Hi @anzin!
Please fix static tests failure:
```
1) Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/var/www/html/app/code/Magento/TwoFactorAuth/Test/Unit/Model/Provider/Engine/GoogleTest.php:25	The class GoogleTest has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.
```

All other tests passed on env with new library

**Comment by anzin** [comment]
@magento run Static Tests

**Comment by xmav** [comment]
@magento import pr to magento-commerce

**Comment by xmav** [comment]
@magento import pr to magento-commerce/security-package

**Comment by m2-github-services** [comment]
@xmav the Pull Request is successfully imported.

**Pull request merged**
